USE PROJETO_SAD

DROP TRIGGER IF EXISTS TG_CHAMADO_AUDITORIA

CREATE TRIGGER TG_CHAMADO_AUDITORIA
ON TB_CHAMADO
AFTER UPDATE 
AS
BEGIN
	IF TRIGGER_NESTLEVEL() < 2 
		UPDATE TB_CHAMADO
		SET DATA_ATUALIZACAO = getdate()
		WHERE ID_CHAMADO IN (SELECT ID_CHAMADO FROM INSERTED)
END