USE PROJETO_SAD

CREATE OR ALTER PROCEDURE SP_INSERT_AUX_CAMPUS (@DATA_CARGA DATETIME) 
AS
BEGIN
	DELETE FROM TB_AUX_CAMPUS WHERE DATA_CARGA = @DATA_CARGA

	INSERT INTO TB_AUX_CAMPUS (DATA_CARGA, COD_CAMPUS, CAMPUS, CNPJ, TELEFONE, CIDADE, BAIRRO, RUA, NUMERO)
	  SELECT @DATA_CARGA, C.ID_CAMPUS, C.NOME, C.CNPJ, C.TELEFONE, E.CIDADE, E.BAIRRO, E.RUA, E.NUMERO
		FROM TB_CAMPUS C
		INNER JOIN TB_ENDERECO E
		ON (C.ID_ENDERECO = E.ID_ENDERECO)
END

EXEC SP_INSERT_AUX_CAMPUS '20221124'

 