USE PROJETO_SAD

CREATE OR ALTER PROCEDURE SP_INSERT_AUX_CATEGORIA(@DATA_CARGA DATETIME)
AS
BEGIN
	INSERT INTO TB_AUX_CATEGORIA(DATA_CARGA, COD_CATEGORIA, CATEGORIA)
	SELECT @DATA_CARGA, C.ID_CATEGORIA, C.CATEGORIA 
	FROM TB_CATEGORIA C
END

EXEC SP_INSERT_AUX_CATEGORIA '20221124'

SELECT * FROM TB_AUX_CATEGORIA