USE PROJETO_SAD

DROP PROCEDURE IF EXISTS SP_INSERT_FATO_CHAMADO

CREATE OR ALTER PROCEDURE SP_INSERT_FATO_CHAMADO(@DATA_CARGA DATETIME)
AS
BEGIN
	DECLARE @DATA_ABERTURA INT, @DATA_FECHAMENTO INT, @ID_CAMPUS INT, @ID_ORGAO_RESPONSAVEL INT, @ID_DEPARTAMENTO INT, @PRIORIDADE VARCHAR(20),
			@ID_CATEGORIA INT, @ID_STATUS INT, @ID_FUNCIONARIO INT, @ID_FUNCIONARIO_ORGAO_RESPONSAVEL INT


	DECLARE @ID_DATA_ANDAMENTO INT, @TEMPO_ABERTURA_ANDAMENTO INT, @TEMPO_ABERTURA_FECHAMENTO INT, @ID_DATA_ABERTURA INT, @ID_DATA_FECHAMENTO INT

	
	DECLARE C_CHAMADO CURSOR FOR
		SELECT DATA_ABERTURA, DATA_FECHAMENTO, PRIORIDADE,
		COD_CATEGORIA, COD_STATUS, COD_DEPARTAMENTO,
		COD_CAMPUS, COD_ORGAO_RESPONSAVEL, COD_REQUISITOR,
		COD_RESOLUTOR
		FROM TB_AUX_CHAMADO
		WHERE DATA_CARGA = @DATA_CARGA

	OPEN C_CHAMADO
	FETCH C_CHAMADO
	INTO @DATA_ABERTURA, @DATA_FECHAMENTO, @PRIORIDADE, @ID_CATEGORIA, @ID_STATUS,
		 @ID_DEPARTAMENTO, @ID_CAMPUS, @ID_ORGAO_RESPONSAVEL, @ID_FUNCIONARIO, @ID_FUNCIONARIO_ORGAO_RESPONSAVEL

	WHILE(@@FETCH_STATUS = 0)
	BEGIN
		
	END
END