USE PROJETO_SAD

DROP PROCEDURE IF EXISTS SP_INSERT_DIM_DEPARTAMENTO

CREATE OR ALTER PROCEDURE SP_INSERT_DIM_DEPARTAMENTO (@DATA_CARGA DATETIME)
AS
BEGIN
	DECLARE @COD_DEP INT, @NOME VARCHAR(80), @SIGLA VARCHAR(10)
	
	DECLARE C_DEPARTAMENTO CURSOR FOR
		SELECT COD_DEPARTAMENTO, DEPARTAMENTO, SIGLA
		FROM TB_AUX_DEPARTAMENTO

	OPEN C_DEPARTAMENTO
	FETCH C_DEPARTAMENTO INTO @COD_DEP, @NOME, @SIGLA

	WHILE(@@FETCH_STATUS = 0)
	BEGIN
		IF EXISTS(SELECT COD_DEPARTAMENTO FROM DIM_DEPARTAMENTO WHERE COD_DEPARTAMENTO = @COD_DEP)
		BEGIN
			UPDATE DIM_DEPARTAMENTO
			SET NM_DEPARTAMENTO = @NOME, SIGLA = @SIGLA
			WHERE COD_DEPARTAMENTO = @COD_DEP
		END

		ELSE
		BEGIN
			INSERT INTO DIM_DEPARTAMENTO
			VALUES(@COD_DEP, @NOME, @SIGLA)
		END

		FETCH C_DEPARTAMENTO INTO @COD_DEP, @NOME, @SIGLA
	END

	CLOSE C_DEPARTAMENTO
	DEALLOCATE C_DEPARTAMENTO
END

EXEC SP_INSERT_DIM_DEPARTAMENTO '20221124'

SELECT * FROM TB_AUX_DEPARTAMENTO

SELECT * FROM TB_DEPARTAMENTO

SELECT * FROM DIM_DEPARTAMENTO