USE PROJETO_SAD

DROP PROCEDURE IF EXISTS SP_INSERT_DIM_FUNCIONARIO

CREATE OR ALTER PROCEDURE SP_INSERT_DIM_FUNCIONARIO (@DATA_CARGA DATETIME) 
AS
BEGIN
	DECLARE @COD_FUNCIONARIO INT, 
			@FUNCIONARIO VARCHAR(20)

	DECLARE C_FUNCIONARIO CURSOR FOR
	  SELECT COD_FUNCIONARIO, FUNCIONARIO FROM TB_AUX_FUNCIONARIO

	OPEN C_FUNCIONARIO 
	FETCH C_FUNCIONARIO INTO @COD_FUNCIONARIO, @FUNCIONARIO
	
	WHILE (@@FETCH_STATUS = 0)
	BEGIN
		IF EXISTS (SELECT COD_FUNCIONARIO FROM DIM_FUNCIONARIO WHERE COD_FUNCIONARIO = @COD_FUNCIONARIO)
		BEGIN
			UPDATE DIM_FUNCIONARIO
			SET NM_FUNCIONARIO = @FUNCIONARIO
			WHERE COD_FUNCIONARIO = @COD_FUNCIONARIO
		END

		ELSE 
		BEGIN
			INSERT INTO DIM_FUNCIONARIO(COD_FUNCIONARIO, NM_FUNCIONARIO)
				VALUES (@COD_FUNCIONARIO, @FUNCIONARIO)
		END
		FETCH C_FUNCIONARIO INTO @COD_FUNCIONARIO, @FUNCIONARIO 
	END
	CLOSE C_FUNCIONARIO
	DEALLOCATE C_FUNCIONARIO
END

EXEC SP_INSERT_DIM_FUNCIONARIO '20101205'

SELECT * FROM DIM_FUNCIONARIO