USE PROJETO_SAD

DROP PROCEDURE IF EXISTS SP_INSERT_DIM_CAMPUS

CREATE OR ALTER PROCEDURE SP_INSERT_DIM_CAMPUS(@DATA_CARGA DATETIME)
AS
BEGIN
	DECLARE @COD_C INT, @NOME VARCHAR(80), @CIDADE VARCHAR(70)

	
	DECLARE C_CAMPUS CURSOR FOR
		SELECT COD_CAMPUS, CAMPUS, CIDADE
		FROM TB_AUX_CAMPUS

	OPEN C_CAMPUS
	FETCH C_CAMPUS INTO @COD_C, @NOME, @CIDADE

	WHILE(@@FETCH_STATUS = 0)
	BEGIN
		IF EXISTS(SELECT COD_CAMPUS FROM DIM_CAMPUS WHERE COD_CAMPUS = @COD_C)
		BEGIN
			UPDATE DIM_CAMPUS
			SET NM_CAMPUS = @NOME, CIDADE = @CIDADE
			WHERE COD_CAMPUS = @COD_C
		END

		ELSE
		BEGIN
			INSERT INTO DIM_CAMPUS
			VALUES(@COD_C, @NOME, @CIDADE)
		END

		FETCH C_CAMPUS INTO @COD_C, @NOME, @CIDADE
	END

	CLOSE C_CAMPUS
	DEALLOCATE C_CAMPUS
END

EXEC SP_INSERT_DIM_CAMPUS '20221124'

SELECT * FROM TB_CAMPUS

SELECT * FROM TB_AUX_CAMPUS

SELECT * FROM DIM_CAMPUS
