USE PROJETO_SAD

DROP PROCEDURE IF EXISTS SP_INSERT_DIM_STATUS

CREATE OR ALTER PROCEDURE SP_INSERT_DIM_STATUS (@DATA_CARGA DATETIME) 
AS
BEGIN
	DECLARE @COD_STATUS INT, 
			@STATUS VARCHAR(20)

	DECLARE C_STATUS CURSOR FOR
	  SELECT COD_STATUS, STATUS FROM TB_AUX_STATUS

	OPEN C_STATUS 
	FETCH C_STATUS INTO @COD_STATUS, @STATUS
	
	WHILE (@@FETCH_STATUS = 0)
	BEGIN
		IF EXISTS (SELECT COD_STATUS FROM DIM_STATUS WHERE COD_STATUS = @COD_STATUS)
		BEGIN
			UPDATE DIM_STATUS
			SET NM_STATUS = @STATUS
			WHERE COD_STATUS = @COD_STATUS
		END

		ELSE 
		BEGIN
			INSERT INTO DIM_STATUS (COD_STATUS, NM_STATUS)
				VALUES (@COD_STATUS, @STATUS)
		END
		FETCH C_STATUS INTO @COD_STATUS, @STATUS 
	END
	CLOSE C_STATUS
	DEALLOCATE C_STATUS
END

EXEC SP_INSERT_DIM_STATUS '20101205'

SELECT * FROM DIM_STATUS