USE PROJETO_SAD

DROP PROCEDURE IF EXISTS SP_INSERT_DIM_CATEGORIA

CREATE OR ALTER PROCEDURE SP_INSERT_DIM_CATEGORIA (@DATA_CARGA DATETIME) 
AS
BEGIN
	DECLARE @COD_CATEGORIA INT, 
			@CATEGORIA VARCHAR(20)

	DECLARE C_CATEGORIA CURSOR FOR
	  SELECT COD_CATEGORIA, CATEGORIA FROM TB_AUX_CATEGORIA

	OPEN C_CATEGORIA 
	FETCH C_CATEGORIA INTO @COD_CATEGORIA, @CATEGORIA
	
	WHILE (@@FETCH_STATUS = 0)
	BEGIN
		IF EXISTS (SELECT COD_CATEGORIA FROM DIM_CATEGORIA WHERE COD_CATEGORIA = @COD_CATEGORIA)
		BEGIN
			UPDATE DIM_CATEGORIA
			SET NM_CATEGORIA = @CATEGORIA
			WHERE COD_CATEGORIA = @COD_CATEGORIA
		END

		ELSE 
		BEGIN
			INSERT INTO DIM_CATEGORIA (COD_CATEGORIA, NM_CATEGORIA)
				VALUES (@COD_CATEGORIA, @CATEGORIA)
		END
		FETCH C_CATEGORIA INTO @COD_CATEGORIA, @CATEGORIA 
	END
	CLOSE C_CATEGORIA
	DEALLOCATE C_CATEGORIA
END

EXEC SP_INSERT_DIM_CATEGORIA '20101205'

SELECT * FROM DIM_CATEGORIA