USE PROJETO_SAD

CREATE OR ALTER PROCEDURE SP_INSERT_AUX_ORGAO_RESPONSAVEL (@DATA_CARGA DATETIME) 
AS
BEGIN
	DELETE FROM TB_AUX_ORGAO_RESPONSAVEL WHERE DATA_CARGA = @DATA_CARGA

	INSERT INTO TB_AUX_ORGAO_RESPONSAVEL (DATA_CARGA, COD_ORGAO_RESPONSAVEL, ORGAO_RESPONSAVEL, SIGLA, COD_CAMPUS,CAMPUS)
	  SELECT @DATA_CARGA, O.ID_ORGAO_RESPONSAVEL, O.NOME, O.SIGLA, C.ID_CAMPUS, C.NOME
	    FROM TB_ORGAO_RESPONSAVEL O
		INNER JOIN TB_CAMPUS C
		ON (C.ID_CAMPUS = O.ID_CAMPUS)
END

EXEC SP_INSERT_AUX_ORGAO_RESPONSAVEL '20221124'

SELECT * FROM TB_AUX_ORGAO_RESPONSAVEL
