USE PROJETO_SAD

CREATE OR ALTER PROCEDURE SP_INSERT_AUX_STATUS (@DATA_CARGA DATETIME) 
AS
BEGIN
	DELETE FROM TB_AUX_STATUS WHERE DATA_CARGA = @DATA_CARGA

	INSERT INTO TB_AUX_STATUS 
	  SELECT @DATA_CARGA, S.ID_STATUS, S.STATUS FROM TB_STATUS S
END


EXEC SP_INSERT_AUX_STATUS '20221124'

SELECT * FROM TB_AUX_STATUS