USE PROJETO_SAD

DROP PROCEDURE IF EXISTS SP_DIM_ORGAO_RESPONSAVEL

CREATE OR ALTER PROCEDURE SP_DIM_ORGAO_RESPONSAVEL(@DATA_CARGA DATETIME)
AS
BEGIN
	DECLARE @COD_OR INT, @NOME VARCHAR(80), @SIGLA VARCHAR(10)

	
	DECLARE C_ORGAO_RESPONSAVEL CURSOR FOR
		SELECT COD_ORGAO_RESPONSAVEL, ORGAO_RESPONSAVEL, SIGLA
		FROM TB_AUX_ORGAO_RESPONSAVEL

	OPEN C_ORGAO_RESPONSAVEL
	FETCH C_ORGAO_RESPONSAVEL INTO @COD_OR, @NOME, @SIGLA

	WHILE(@@FETCH_STATUS = 0)
	BEGIN
		IF EXISTS(SELECT COD_ORGAO_RESPONSAVEL FROM DIM_ORGAO_RESPONSAVEL WHERE COD_ORGAO_RESPONSAVEL = @COD_OR)
		BEGIN
			UPDATE DIM_ORGAO_RESPONSAVEL
			SET NM_ORGAO_RESPONSAVEL = @NOME, SIGLA = @SIGLA
			WHERE COD_ORGAO_RESPONSAVEL = @COD_OR
		END

		ELSE
		BEGIN
			INSERT INTO DIM_ORGAO_RESPONSAVEL
			VALUES(@COD_OR, @NOME, @SIGLA)
		END

		FETCH C_ORGAO_RESPONSAVEL INTO @COD_OR, @NOME, @SIGLA
	END

	CLOSE C_ORGAO_RESPONSAVEL
	DEALLOCATE C_ORGAO_RESPONSAVEL
END

EXEC SP_DIM_ORGAO_RESPONSAVEL '20221124'

SELECT * FROM TB_AUX_ORGAO_RESPONSAVEL

SELECT * FROM TB_ORGAO_RESPONSAVEL

SELECT * FROM DIM_ORGAO_RESPONSAVEL