USE PROJETO_SAD

CREATE OR ALTER PROCEDURE SP_INSERT_AUX_FUNCIONARIO(@DATA_CARGA DATETIME)
AS
BEGIN
	DELETE FROM TB_AUX_FUNCIONARIO WHERE DATA_CARGA = @DATA_CARGA

	INSERT INTO TB_AUX_FUNCIONARIO(DATA_CARGA, COD_FUNCIONARIO, FUNCIONARIO, COD_DEPARTAMENTO, DEPARTAMENTO,
									COD_ORGAO_RESPONSAVEL, ORGAO_RESPONSAVEL, FUNCIONARIO_ORGAO_RESPONSAVEL,
									COD_CAMPUS, CAMPUS)
	SELECT @DATA_CARGA, F.ID_FUNCIONARIO, F.NOME, D.ID_DEPARTAMENTO,
	D.NOME, NULL, NULL, 'NAO', C.ID_CAMPUS, C.NOME
	FROM TB_FUNCIONARIO F
	JOIN TB_DEPARTAMENTO D
	ON (F.ID_DEPARTAMENTO = D.ID_DEPARTAMENTO)
	JOIN TB_CAMPUS C
	ON(D.ID_CAMPUS = C.ID_CAMPUS)

	UNION ALL

	SELECT @DATA_CARGA, F.ID_FUNCIONARIO, F.NOME, NULL, NULL, O.ID_ORGAO_RESPONSAVEL,
	O.NOME, 'SIM', C.ID_CAMPUS, C.NOME
	FROM TB_FUNCIONARIO F
	JOIN TB_ORGAO_RESPONSAVEL O
	ON(F.ID_ORGAO_RESPONSAVEL = O.ID_ORGAO_RESPONSAVEL)
	JOIN TB_CAMPUS C
	ON(O.ID_CAMPUS = C.ID_CAMPUS) 
END

EXEC SP_INSERT_AUX_FUNCIONARIO '20221124'

SELECT * FROM TB_AUX_FUNCIONARIO
