USE PROJETO_SAD

CREATE OR ALTER PROCEDURE SP_INSERT_AUX_DEPARTAMENTO (@DATA_CARGA DATETIME) 
AS
BEGIN
	DELETE FROM TB_AUX_DEPARTAMENTO WHERE DATA_CARGA = @DATA_CARGA

	INSERT INTO TB_AUX_DEPARTAMENTO (DATA_CARGA, COD_DEPARTAMENTO, DEPARTAMENTO, SIGLA, DESCRICAO, COD_CAMPUS, CAMPUS)
	  SELECT @DATA_CARGA, D.ID_DEPARTAMENTO, D.NOME, D.SIGLA, D.DESCRICAO, C.ID_CAMPUS, C.NOME
	    FROM TB_DEPARTAMENTO D
		INNER JOIN TB_CAMPUS C
		ON (C.ID_CAMPUS = D.ID_CAMPUS)
END

EXEC SP_INSERT_AUX_DEPARTAMENTO '20221124'

SELECT * FROM TB_AUX_DEPARTAMENTO