USE PROJETO_SAD

DROP TABLE IF EXISTS FATO_CHAMADO
DROP TABLE IF EXISTS DIM_CAMPUS
DROP TABLE IF EXISTS DIM_CATEGORIA
DROP TABLE IF EXISTS DIM_DEPARTAMENTO
DROP TABLE IF EXISTS DIM_FUNCIONARIO
DROP TABLE IF EXISTS DIM_ORGAO_RESPONSAVEL
DROP TABLE IF EXISTS DIM_STATUS
DROP TABLE IF EXISTS DIM_TEMPO


CREATE TABLE DIM_TEMPO(
	ID_TEMPO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	NIVEL CHAR(3) NOT NULL CHECK(NIVEL IN ('DIA','MES','ANO')),
	DATA DATETIME NULL,
	DIA INT NULL,
	NM__DIA VARCHAR(25) NULL,
	FIM_SEMANA CHAR(3) NULL CHECK(fim_semana IN ('SIM','NAO')),
	MES INT NULL,
	NM__MES VARCHAR(20) NULL,
	TIMESTRE INT NULL,
	NM_TRIMESTRE VARCHAR(45) NULL,
	SEMESTRE INT NULL,
	NM__SEMESTRE VARCHAR(45) NULL,
	ANO INT NOT NULL
)

CREATE TABLE DIM_DEPARTAMENTO(
	ID_DEPARTAMENTO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	COD_DEPARTAMENTO INT NOT NULL,
	NM_DEPARTAMENTO VARCHAR(80) NOT NULL,
	SIGLA VARCHAR(10) NOT NULL
)

CREATE TABLE DIM_ORGAO_RESPONSAVEL(
	ID_ORGAO_RESPONSAVEL INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	COD_ORGAO_RESPONSAVEL INT NOT NULL,
	NM_ORGAO_RESPONSAVEL VARCHAR(80) NOT NULL,
	SIGLA VARCHAR(10) NOT NULL
)

CREATE TABLE DIM_CATEGORIA (
	ID_CATEGORIA INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	COD_CATEGORIA INT NOT NULL,
	NM_CATEGORIA VARCHAR(45) NOT NULL
)
CREATE TABLE DIM_STATUS (
	ID_STATUS INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	COD_STATUS INT NOT NULL,
	NM_STATUS VARCHAR(45) NOT NULL
)
CREATE TABLE DIM_CAMPUS (
	ID_CAMPUS INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	COD_CAMPUS INT NOT NULL,
	NM_CAMPUS VARCHAR(80) NOT NULL,
	CIDADE VARCHAR(70) NOT NULL
)
CREATE TABLE DIM_FUNCIONARIO (
	ID_FUNCIONARIO INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	COD_FUNCIONARIO INT NOT NULL,
	NM_FUNCIONARIO VARCHAR(80) NOT NULL
)

CREATE TABLE FATO_CHAMADO(
	ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	QUANTIDADE INT DEFAULT(1) NOT NULL,
	TEMPO_ABERTURA_ANDAMENTO INT NULL,
	TEMPO_ABERTURA_FECHAMENTO INT NULL,
	PRIORIDADE VARCHAR(10) NOT NULL,

	ID_CAMPUS INT FOREIGN KEY REFERENCES DIM_CAMPUS(ID_CAMPUS) NOT NULL,
	ID_ORGAO_RESPONSAVEL INT FOREIGN KEY REFERENCES DIM_ORGAO_RESPONSAVEL(ID_ORGAO_RESPONSAVEL) NOT NULL,
	ID_DEPARTAMENTO INT FOREIGN KEY REFERENCES DIM_DEPARTAMENTO(ID_DEPARTAMENTO) NOT NULL,

	ID_CATEGORIA INT FOREIGN KEY REFERENCES DIM_CATEGORIA(ID_CATEGORIA) NOT NULL,
	ID_STATUS INT FOREIGN KEY REFERENCES DIM_STATUS(ID_STATUS) NOT NULL,

	ID_FUNCIONARIO INT FOREIGN KEY REFERENCES DIM_FUNCIONARIO(ID_FUNCIONARIO) NOT NULL,
	ID_FUNCIONARIO_ORGAO_RESPONSAVEL INT FOREIGN KEY REFERENCES DIM_FUNCIONARIO(ID_FUNCIONARIO) NULL,

	DATA_ABERTURA INT FOREIGN KEY REFERENCES DIM_TEMPO(ID_TEMPO) NOT NULL,
	DATA_FECHAMENTO INT FOREIGN KEY REFERENCES DIM_TEMPO(ID_TEMPO) NULL,
	DATA_ANDAMENTO INT FOREIGN KEY REFERENCES DIM_TEMPO(ID_TEMPO) NULL
)
